Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "src/parrallelimport.py", line 175, in <module>
    main()
  File "src/parrallelimport.py", line 127, in main
    x, totalProcessingTime, start_time, end_time = readInData(startingRow+start, startingRow+stop, fileName)
  File "src/parrallelimport.py", line 46, in readInData
    chunks = pd.read_csv(fileName, skiprows =lambda x: x not in range(startingRow, endingRow ),chunksize=chunkSize)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1235, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 551, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "src/parrallelimport.py", line 175, in <module>
    main()
  File "src/parrallelimport.py", line 127, in main
    x, totalProcessingTime, start_time, end_time = readInData(startingRow+start, startingRow+stop, fileName)
  File "src/parrallelimport.py", line 46, in readInData
    chunks = pd.read_csv(fileName, skiprows =lambda x: x not in range(startingRow, endingRow ),chunksize=chunkSize)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1235, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/group16/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 551, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 62
slurmstepd: error: *** STEP 19485.0 ON jaguar3 CANCELLED AT 2022-05-16T22:27:49 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: jaguar9: tasks 24-27: Killed
srun: error: jaguar5: tasks 8-11: Killed
srun: error: jaguar4: tasks 4-7: Killed
srun: error: jaguar3: tasks 0-3: Killed
srun: error: jaguar6: tasks 12-15: Killed
srun: error: jaguar7: tasks 16-19: Killed
srun: error: jaguar18: tasks 60-62: Killed
srun: error: jaguar15: tasks 48-51: Killed
srun: error: jaguar17: tasks 56-59: Killed
srun: error: jaguar11: tasks 32-35: Killed
srun: error: jaguar10: tasks 28-31: Killed
srun: error: jaguar14: tasks 44-47: Killed
srun: error: jaguar13: tasks 40-43: Killed
srun: error: jaguar12: tasks 36-39: Killed
srun: error: jaguar8: tasks 20,22-23: Killed
srun: error: jaguar16: tasks 52-55: Killed
srun: error: jaguar18: task 63: Killed
srun: error: jaguar8: task 21: Killed
